# Emergent Product Portfolio
# Defines the product lines, their relationships, and brand associations
# Schema: schemas/product_portfolio_schema.json

portfolio:
  id: "portfolio-emergent"
  name: "Emergent Ecosystem Portfolio"
  description: |
    Emergent is an ecosystem of AI-powered products, frameworks, and tools designed
    to help organizations achieve emergent understanding—the ability to see patterns,
    connections, and insights that only become visible when information is properly
    structured, connected, and AI-enhanced.
    
    The portfolio combines a core knowledge platform (Emergent Core) with product
    development methodologies (EPF, OpenSpec) and developer tools to create an
    integrated offering for knowledge-intensive organizations.
  version: "1.0.0"
  
  organization:
    name: "Emergent"
    legal_entity: "Eyedea AS"

  # ============================================================================
  # PRODUCT LINES
  # ============================================================================
  product_lines:
    # --------------------------------------------------------------------------
    # Emergent Core: The Knowledge Engine
    # --------------------------------------------------------------------------
    - id: "pl-emergent-core"
      name: "Emergent Core"
      codename: "Core"
      type: "platform"
      description: |
        AI-powered knowledge platform that transforms documents into queryable
        knowledge graphs with automatic entity extraction, semantic search,
        and grounded AI chat. The engine that powers emergent understanding.
        Formerly known as "Spec Server".
      value_model_ref: "product.core.value_model.yaml"
      status: "development"
      target_market:
        segments:
          - "Product Teams"
          - "Developers"
          - "Knowledge Workers"
          - "Consultancies"
        verticals:
          - "Software Development"
          - "Professional Services"
          - "Research & Academia"
          - "Legal & Compliance"
        geographies:
          - "Global"
          - "Initial focus: Europe, North America"
      key_components:
        - component_ref: "DocumentIngestion"
          role: core
        - component_ref: "EntityExtraction"
          role: core
        - component_ref: "KnowledgeGraph"
          role: core
        - component_ref: "SemanticSearch"
          role: core
        - component_ref: "AIChat"
          role: core
        - component_ref: "MCPIntegration"
          role: supporting
        - component_ref: "AdminUI"
          role: supporting
      versioning:
        current_version: "0.1.0"
        version_strategy: "semver"
        release_cadence: "continuous"
      dependencies:
        requires_product_lines: []
        external_dependencies:
          - "PostgreSQL with pgvector"
          - "Google Gemini API (embeddings & LLM)"
          - "Zitadel (authentication)"
          - "Cloud Infrastructure"

    # --------------------------------------------------------------------------
    # EPF: Emergent Product Framework
    # --------------------------------------------------------------------------
    - id: "pl-epf"
      name: "Emergent Product Framework"
      codename: "EPF"
      type: "service"
      description: |
        A structured methodology for product development with three phases:
        READY (strategy → roadmap), FIRE (execution), and AIM (assessment).
        Schema-driven, AI-compatible, and designed for multi-product portfolios.
      value_model_ref: "product.epf.value_model.yaml"
      status: "active"
      target_market:
        segments:
          - "Product Managers"
          - "Product Teams"
          - "Startup Founders"
        verticals:
          - "Software Development"
          - "Product Organizations"
        geographies:
          - "Global"
      key_components:
        - component_ref: "PhaseTemplates"
          role: core
        - component_ref: "JSONSchemas"
          role: core
        - component_ref: "AIWizards"
          role: supporting
        - component_ref: "InstanceManagement"
          role: supporting
      versioning:
        current_version: "1.10.1"
        version_strategy: "semver"
        release_cadence: "on-demand"
      dependencies:
        requires_product_lines: []
        external_dependencies:
          - "Git (version control)"
          - "YAML/JSON editors"

    # --------------------------------------------------------------------------
    # OpenSpec: AI-Assisted Specifications
    # --------------------------------------------------------------------------
    - id: "pl-openspec"
      name: "OpenSpec"
      codename: "OpenSpec"
      type: "service"
      description: |
        AI-assisted specification and proposal management framework. Helps teams
        create, review, and track technical specifications with structured
        templates and AI-enhanced drafting.
      value_model_ref: "product.openspec.value_model.yaml"
      status: "development"
      target_market:
        segments:
          - "Engineering Teams"
          - "Technical Leads"
          - "Architects"
        verticals:
          - "Software Development"
        geographies:
          - "Global"
      key_components:
        - component_ref: "SpecTemplates"
          role: core
        - component_ref: "ProposalWorkflow"
          role: core
        - component_ref: "AIDrafting"
          role: supporting
      versioning:
        current_version: "0.1.0"
        version_strategy: "semver"
        release_cadence: "on-demand"
      dependencies:
        requires_product_lines: []
        external_dependencies:
          - "Git (version control)"
          - "AI Assistant (Claude, GPT, etc.)"

    # --------------------------------------------------------------------------
    # Emergent Tools: CLI & Integrations
    # --------------------------------------------------------------------------
    - id: "pl-emergent-tools"
      name: "Emergent Tools"
      codename: "Tools"
      type: "software"
      description: |
        Command-line interfaces, MCP servers, and integration adapters that
        extend the Emergent ecosystem and connect with third-party systems.
        Enables automation, AI agent integration, and external system sync.
      value_model_ref: "product.tools.value_model.yaml"
      status: "concept"
      target_market:
        segments:
          - "Developers"
          - "DevOps Engineers"
          - "AI Agent Builders"
        verticals:
          - "Software Development"
        geographies:
          - "Global"
      key_components:
        - component_ref: "EmergentCLI"
          role: core
        - component_ref: "MCPServer"
          role: core
        - component_ref: "IntegrationAdapters"
          role: supporting
      versioning:
        current_version: "0.0.1"
        version_strategy: "semver"
        release_cadence: "on-demand"
      dependencies:
        requires_product_lines:
          - "pl-emergent-core"
        external_dependencies:
          - "Node.js runtime"
          - "Third-party APIs (ClickUp, Notion, etc.)"

  # ============================================================================
  # PRODUCT LINE RELATIONSHIPS
  # ============================================================================
  product_line_relationships:
    - id: "plr-tools-extends-core"
      from_product_line: "pl-emergent-tools"
      to_product_line: "pl-emergent-core"
      relationship_type: "depends_on"
      description: |
        Emergent Tools extends Core functionality by providing CLI access,
        MCP server for AI agents, and integration adapters. Tools require
        Core's APIs to function.
      integration_points:
        - from_component: "EmergentCLI"
          to_component: "CoreAPI"
          integration_type: "api"
          description: "CLI commands call Core REST/GraphQL APIs"
        - from_component: "MCPServer"
          to_component: "SemanticSearch"
          integration_type: "api"
          description: "MCP tools expose Core search to AI agents"
        - from_component: "IntegrationAdapters"
          to_component: "DocumentIngestion"
          integration_type: "data_flow"
          description: "Adapters sync external content into Core"
      bidirectional: false

    - id: "plr-epf-enhances-core"
      from_product_line: "pl-epf"
      to_product_line: "pl-emergent-core"
      relationship_type: "enhances"
      description: |
        EPF artifacts can be stored in Core's knowledge graph, enabling
        AI-powered search and chat over product strategy documents.
        Core's extraction can understand EPF schema structures.
      integration_points:
        - from_component: "PhaseTemplates"
          to_component: "DocumentIngestion"
          integration_type: "data_flow"
          description: "EPF YAML files ingested into Core knowledge base"
        - from_component: "AIWizards"
          to_component: "AIChat"
          integration_type: "api"
          description: "EPF wizards leverage Core's RAG capabilities"
      bidirectional: true

    - id: "plr-openspec-integrates-core"
      from_product_line: "pl-openspec"
      to_product_line: "pl-emergent-core"
      relationship_type: "integrates_with"
      description: |
        OpenSpec specifications can be stored and searched in Core.
        Core's AI can help draft specifications based on existing
        knowledge in the graph.
      integration_points:
        - from_component: "SpecTemplates"
          to_component: "DocumentIngestion"
          integration_type: "data_flow"
          description: "Specifications ingested into knowledge base"
        - from_component: "AIDrafting"
          to_component: "AIChat"
          integration_type: "api"
          description: "Spec drafting uses Core's RAG for context"
      bidirectional: true

  # ============================================================================
  # BRANDS
  # ============================================================================
  brands:
    - id: "brand-emergent"
      name: "Emergent"
      type: "master"
      description: |
        The umbrella brand for the entire ecosystem. Represents the core
        value proposition of "emergent understanding" - insights that arise
        from properly connected, AI-enhanced information.
      status: "active"
      applies_to:
        product_lines:
          - "pl-emergent-core"
          - "pl-epf"
          - "pl-openspec"
          - "pl-emergent-tools"
      brand_elements:
        tagline: "Where understanding emerges from information"
        value_proposition_summary: |
          Emergent helps organizations achieve emergent understanding—seeing
          patterns, connections, and insights that only become visible when
          information is properly structured, connected, and AI-enhanced.
        brand_personality:
          - "Intelligent"
          - "Approachable"
          - "Developer-friendly"
          - "Principled"

    - id: "brand-epf"
      name: "EPF"
      type: "product"
      description: |
        The Emergent Product Framework brand. Used for the methodology,
        documentation, and related tooling.
      status: "active"
      applies_to:
        product_lines:
          - "pl-epf"
      brand_elements:
        tagline: "Structured product development"
        value_proposition_summary: |
          EPF brings structure to product development through three clear
          phases (READY, FIRE, AIM) with schema-driven artifacts that enable
          machine-readable planning and AI-assisted content generation.

  # ============================================================================
  # OFFERINGS (Future)
  # ============================================================================
  offerings: []
  # Offerings will be defined when products reach market readiness.
  # Examples that may be added:
  # - Emergent Core Cloud (SaaS offering)
  # - Emergent Core Enterprise (self-hosted)
  # - EPF Professional (training + support)
