version: 2

project_name: epf-cli

before:
  hooks:
    - apps/epf-cli/scripts/sync-embedded.sh

builds:
  - id: epf-cli
    dir: apps/epf-cli
    binary: epf-cli
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
      - -X github.com/emergent-company/emergent-strategy/apps/epf-cli/internal/version.Version={{ .Version }}
      - -X github.com/emergent-company/emergent-strategy/apps/epf-cli/internal/version.GitCommit={{ .ShortCommit }}
      - -X github.com/emergent-company/emergent-strategy/apps/epf-cli/internal/version.BuildDate={{ .Date }}
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64

archives:
  - id: default
    formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: checksums.txt

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
      - "^chore\\(deps\\):"

brews:
  - name: epf-cli
    repository:
      owner: emergent-company
      name: homebrew-emergent
      token: "{{ .Env.TAP_GITHUB_TOKEN }}"
    directory: Formula
    homepage: "https://github.com/emergent-company/emergent.strategy"
    description: "CLI tool for the Emergent Product Framework (EPF) — validation, health checks, and MCP tooling for AI-assisted strategy"
    license: "Apache-2.0"
    install: |
      bin.install "epf-cli"
    test: |
      system bin/"epf-cli", "version"
    commit_msg_template: "chore: update epf-cli formula to {{ .Tag }}"

release:
  name_template: "EPF CLI v{{ .Version }}"
