-- Migration: Add debug info storage for object extraction jobs
-- Description: Persist structured timeline/debug output generated by the extraction worker
-- Purpose: Ensure UI can render extraction timelines and debugging metadata
-- Date: 2025-10-19
-- Related: Extraction worker timeline instrumentation (apps/server-nest/src/modules/extraction-jobs/extraction-worker.service.ts)
-- =============================================================================
-- Add debug_info column (JSONB) for storing timeline and raw provider payloads
ALTER TABLE
    kb.object_extraction_jobs
ADD
    COLUMN IF NOT EXISTS debug_info JSONB;

COMMENT ON COLUMN kb.object_extraction_jobs.debug_info IS 'Structured debug information emitted by the extraction worker (timeline, provider payloads, counters)';
