# Emergent Core Product Line Value Model
# Defines the value delivered by Emergent Core - the knowledge engine
#
# METAPHOR: The Brain - Intelligence, memory, and reasoning
# WHY: Organizations have scattered knowledge in disconnected tools
# HOW: AI-powered knowledge graph + semantic search + RAG
# WHAT: Document intelligence platform for organizational knowledge
#
# This is a PRODUCT LINE VALUE MODEL (not workspace-level).
# It shares the North Star with other Emergent product lines (Runtime, Tools).
#
# Schema migration note: Added track_name for EPF 2.11.0 compliance.
# Custom fields (product_line_id, etc.) retained in high_level_model.
#
track_name: "Product"
version: "1.0.0"
status: "active"
packaged_default: false
activation_notes: |
  Core is production-ready and actively used. This model reflects current
  capabilities with planned enhancements marked as inactive. MVP complete.
description: |
  Emergent Core is the knowledge engine that transforms organizational documents
  into a queryable knowledge graph. It ingests content from any source, extracts
  entities and relationships using AI, and enables semantic search and AI chat
  grounded in your documents with source citations.
  
  ARCHITECTURE: Core provides the shared infrastructure (auth, multi-tenancy,
  RLS, database) that other Emergent products build upon. It exposes knowledge
  via MCP (Model Context Protocol) for AI agent integration.
high_level_model:
  product_line_id: "pl-emergent-core"
  product_line_name: "Emergent Core"
  formerly_known_as: "Spec Server"
  last_updated: "2025-12-30"
  product_mission: |
    Give organizations a unified, AI-accessible knowledge layer that connects
    strategy, documentation, and code—transforming scattered information into
    connected intelligence that both humans and AI agents can reason over.
  
  main_goal: "Eliminate knowledge silos and context blindness in product teams"
  
  product_goals:
    - "Make all organizational knowledge searchable by meaning, not just keywords"
    - "Enable AI agents to understand product context beyond just code"
    - "Automatically extract structured knowledge from unstructured documents"
    - "Provide trustworthy AI answers with source citations"
    - "Create the context layer that connects strategy → knowledge → code"
  
  value_delivery_description:
    - "Teams upload documents or connect integrations (ClickUp, Google Drive)"
    - "AI extracts entities (features, people, concepts) and relationships automatically"
    - "Knowledge graph grows and connects information across documents"
    - "Users search by meaning using hybrid semantic + full-text search"
    - "AI chat answers questions with citations back to source documents"
    - "External AI tools (Cursor, Claude) access knowledge via MCP protocol"
  
  needs_addressed:
    - "Product strategy lives in slide decks nobody reads"
    - "Documentation is scattered across Notion, Confluence, Google Docs, wikis"
    - "Developers can't find architecture decisions or design rationale"
    - "AI coding assistants (Copilot, Cursor) lack product context"
    - "New team members take weeks to understand existing knowledge"
    - "Same questions answered repeatedly because knowledge isn't discoverable"
  
  values_delivered:
    - "Single source of truth for organizational knowledge"
    - "AI that understands your product, not just generic code patterns"
    - "Automatic knowledge connections you didn't know existed"
    - "Trustworthy answers with source citations (not hallucinations)"
    - "Onboarding time reduced from weeks to days"
    - "Knowledge accessible where teams already work (Slack, IDE, browser)"
  
  solution_steps:
    - "Connect your knowledge sources (upload, integrate, or paste URLs)"
    - "AI extracts entities and builds knowledge graph automatically"
    - "Search by meaning or ask questions in natural language"
    - "Get instant answers with citations to source documents"
    - "Integrate with AI coding assistants via MCP protocol"
    - "Knowledge evolves as you add more content"

# Note: Detailed layer structure available in internal documentation.
# This high-level model focuses on strategic value delivery and integration points.

# ============================================================================
# INTEGRATION POINTS WITH OTHER PRODUCT LINES
# ============================================================================
  ecosystem_integration:
  epf_runtime:
    description: "Runtime uses Core for artifact storage and shares auth/multi-tenancy infrastructure"
    integration_points:
      - "EPF artifacts (roadmaps, features) stored as Core documents"
      - "Workflow execution history searchable via Core"
      - "Shared Zitadel authentication and RLS policies"
      - "Unified project scoping (same org → project hierarchy)"
  
  emergent_tools:
    description: "Tools connect external systems to Core and expose Core knowledge in third-party platforms"
    integration_points:
      - "CLI uses Core APIs for bulk operations"
      - "Git Bridge ingests commit messages and PRs as Core documents"
      - "Slack Bot queries Core via MCP for real-time answers"
      - "Integration adapters (ClickUp, Notion) feed Core ingestion"
# [ ] No technical acronyms in names/UVPs (API, DB, K8s, JSON, XML)
# [ ] All UVPs follow pattern: "{Deliverable} so that {beneficiary} can {capability}, which helps us {progress}"
# [ ] Technical details in context tags prefixed "Technical:"
# [ ] Can non-technical investor understand main content? (5-question test)

layers:
  - id: core-knowledge-platform
    name: Core Knowledge Platform
    active: true
    description: |
      Foundational AI-powered knowledge infrastructure that transforms documents
      into queryable knowledge graphs. Covers document ingestion, entity extraction,
      semantic search, and AI chat with citations.
    components:
      - id: document-intelligence
        name: Document Intelligence
        active: true
        subs:
          - id: document-ingestion
            name: Document Ingestion
            active: true
          - id: entity-extraction
            name: Entity Extraction
            active: true
          - id: knowledge-graph
            name: Knowledge Graph
            active: true
      - id: knowledge-access
        name: Knowledge Access
        active: true
        subs:
          - id: semantic-search
            name: Semantic Search
            active: true
          - id: ai-chat
            name: AI Chat
            active: true

