# Emergent Tools Product Line Value Model
# METAPHOR: The Circulatory System - Connectors, bridges, and interfaces

# WHY: Knowledge systems create value when integrated into existing workflows
# HOW: Build adapters that connect Core/Runtime to where teams already work
# WHAT: Suite of tools that close feedback loops between strategy, code, deployment, and users

# Schema migration note: Added track_name and layers for EPF 2.11.0 compliance.
# Custom fields (categories, tier_1_roadmap, etc.) retained in high_level_model.

track_name: "Product"
version: "1.0.0"
status: "active"
packaged_default: false
activation_notes: |
  Tools product line currently in planning phase. Building on brainstorm from
  Dec 2025 that identified 8 tool categories and 20+ specific integration points.
  
  MVP STRATEGY: Launch Tier 1 tools first (Git Bridge, Deploy Tracker, Slack Bot,
  SDK) to validate integration patterns before expanding to full catalog.
description: |
  Emergent Tools is the integration layer connecting Core and Runtime to external
  systems. Closes feedback loops: Strategy→Code (Git Bridge), Code→Production
  (Deploy Tracker), Users→Strategy (Feedback Aggregator), Team→Knowledge (Slack).
  
  ARCHITECTURE: Tools are lightweight adapters that consume Core/Runtime APIs
  and expose functionality in third-party platforms (Slack, Git, CI/CD, etc.)

high_level_model:
  product_line_id: "pl-emergent-tools"
  product_line_name: "Emergent Tools"
  last_updated: "2025-12-30"
  product_mission: |
    Make Emergent knowledge and workflows accessible where teams already work,
    creating automatic connections between strategy, code, deployment, and user
    feedback without forcing tool consolidation.
  
  main_goal: "Close feedback loops by integrating Emergent into existing workflows"
  
  product_goals:
    - "Connect strategy artifacts (EPF features) to code commits and PRs"
    - "Track feature deployment status from roadmap → production"
    - "Aggregate user feedback into searchable knowledge in Core"
    - "Make Core knowledge accessible in Slack, CLI, and IDEs"
    - "Enable developers to extend Emergent with custom integrations"
  
  value_delivery_description:
    - "Developer commits code referencing feature IDs (Git Bridge captures context)"
    - "CI/CD deploys feature (Deploy Tracker updates status in Runtime)"
    - "Users give feedback via surveys/support (Feedback Aggregator ingests to Core)"
    - "Team asks questions in Slack (Bot queries Core via MCP)"
    - "Product manager sees complete loop: feature → code → deploy → feedback"
  
  needs_addressed:
    - "Strategy documents disconnect from actual code being shipped"
    - "No visibility into what features are deployed vs planned"
    - "User feedback scattered across support tickets, surveys, sales calls"
    - "Teams must context-switch to separate tools to access knowledge"
    - "No programmatic way to extend platform for custom workflows"
  
  values_delivered:
    - "Automatic connection between strategy artifacts and Git commits"
    - "Real-time deployment status visible in strategy/roadmap tools"
    - "Unified view of user feedback tied to features and releases"
    - "Knowledge accessible in Slack (no tool switching required)"
    - "Developer extensibility via SDK and CLI"
  
  solution_steps:
    - "Install Git Bridge in repository (GitHub Actions or webhook)"
    - "Configure Deploy Tracker in CI/CD pipeline"
    - "Connect Feedback Aggregator to survey/support tools"
    - "Add Slack Bot to workspace channels"
    - "Use SDK/CLI for custom integrations and bulk operations"

  # Tool categories moved into high_level_model
  categories:
  - category_id: "code-integration"
    category_name: "Code Integration Tools"
    description: "Connect strategy artifacts to source code and development workflows"
    tier_1_tools:
      - name: "Git Bridge"
        uvp: "Feature IDs referenced in commits automatically link strategy → code"
        integration: "GitHub Actions / GitLab CI / Bitbucket Pipelines"
      - name: "SDK"
        uvp: "Developers extend Emergent with custom integrations using TypeScript/Python"
        integration: "npm / PyPI package with Core/Runtime API clients"
  
  - category_id: "deployment-observability"
    category_name: "Deployment & Observability Tools"
    description: "Track feature deployment status and system health"
    tier_1_tools:
      - name: "Deploy Tracker"
        uvp: "Feature deployment status automatically updates in roadmap/Runtime workflows"
        integration: "CI/CD webhooks (Jenkins, CircleCI, GitHub Actions)"
  
  - category_id: "collaboration"
    category_name: "Collaboration & Workflow Tools"
    description: "Make knowledge accessible in communication platforms"
    tier_1_tools:
      - name: "Slack Bot"
        uvp: "Teams query Core knowledge directly in Slack channels (no context switching)"
        integration: "Slack App with MCP protocol integration"
  
  - category_id: "customer-feedback"
    category_name: "Customer Feedback Tools"
    description: "Aggregate external feedback into Core knowledge"
    tier_2_tools:
      - name: "Feedback Aggregator"
        uvp: "User feedback from surveys/support automatically categorized and linked to features"
        integration: "Webhooks from Zendesk, Intercom, SurveyMonkey"
  
  - category_id: "developer-experience"
    category_name: "Developer Experience Tools"
    description: "CLI, templates, and code generation for developers"
    tier_2_tools:
      - name: "CLI"
        uvp: "Bulk operations, local development, and scripting via command line"
        integration: "Standalone binary (Go/Rust) with Core/Runtime API client"
  
  - category_id: "intelligence-automation"
    category_name: "Intelligence & Automation Tools"
    description: "AI-powered workflow automation and insights"
    tier_3_tools:
      - name: "Workflow Automator"
        uvp: "Trigger Runtime workflows based on external events (deploy, feedback, commit)"
        integration: "Event bus connecting external systems to Runtime"
  
  - category_id: "governance-compliance"
    category_name: "Governance & Compliance Tools"
    description: "Audit logging, access control, and data lineage"
    tier_3_tools:
      - name: "Audit Logger"
        uvp: "Comprehensive audit trail for compliance and security review"
        integration: "Centralized logging with SIEM integration (Splunk, Datadog)"
  
  - category_id: "enterprise-integration"
    category_name: "Enterprise Integration Tools"
    description: "SSO, API gateway, backup/restore for enterprise customers"
    tier_4_tools:
      - name: "SSO Connector"
        uvp: "Enterprise customers use existing identity providers (Okta, Azure AD)"
        integration: "SAML / OIDC adapter extending Zitadel"

# ============================================================================
# TIER 1 PRIORITIES (MVP PLATFORM)
# ============================================================================
tier_1_roadmap:
  priority_tools:
    - name: "Git Bridge"
      rationale: "Closes strategy → code feedback loop (highest customer demand)"
      dependencies: ["Core document API", "Runtime feature tracking"]
      mvp_scope: "GitHub Actions integration with commit message parsing"
      effort: "2-3 weeks"
    
    - name: "Deploy Tracker"
      rationale: "Closes code → production visibility gap (critical for PMs)"
      dependencies: ["Runtime workflow API", "Core document updates"]
      mvp_scope: "Webhook endpoint for CI/CD pipelines, status updates"
      effort: "1-2 weeks"
    
    - name: "Slack Bot"
      rationale: "Makes knowledge accessible where teams work (adoption driver)"
      dependencies: ["Core MCP server", "Slack App manifest"]
      mvp_scope: "Query Core via slash commands, inline search"
      effort: "2 weeks"
    
    - name: "SDK (TypeScript)"
      rationale: "Enables customer extensions and custom integrations"
      dependencies: ["Core/Runtime API stability", "OpenAPI spec"]
      mvp_scope: "TypeScript client with authentication and type safety"
      effort: "1 week"

# ============================================================================
# INTEGRATION POINTS WITH OTHER PRODUCT LINES
# ============================================================================
ecosystem_integration:
  emergent_core:
    description: "Tools ingest external data into Core and query Core knowledge"
    integration_points:
      - "Git Bridge ingests commits/PRs as Core documents"
      - "Feedback Aggregator creates Core documents from user feedback"
      - "Slack Bot queries Core via MCP protocol"
      - "CLI uses Core bulk upload API for batch operations"
  
  epf_runtime:
    description: "Tools trigger Runtime workflows and display workflow status"
    integration_points:
      - "Deploy Tracker updates feature deployment status in Runtime"
      - "Workflow Automator triggers Runtime workflows from external events"
      - "Slack Bot displays active workflow status and history"
      - "CLI can start/stop Runtime workflows programmatically"
  
  external_systems:
    description: "Tools act as adapters between Emergent and third-party platforms"
    integration_patterns:
      - "Webhooks (inbound): CI/CD → Deploy Tracker, Feedback → Aggregator"
      - "API clients (outbound): Core/Runtime → Slack, Git, email"
      - "Event-driven: External system events trigger Runtime workflows"
      - "Bidirectional sync: Git Bridge two-way link between strategy and code"

  success_metrics:
    adoption:
      - "% of teams using at least one Tool"
      - "Average tools per customer (cross-selling indicator)"
      - "Time-to-first-value after Tool installation"
    
    integration_health:
      - "API call success rate (uptime for external dependencies)"
      - "Integration setup completion rate"
      - "Error rate in webhook processing"
    
    feedback_loop_closure:
      - "% of features with Git commits linked"
      - "Average time: feature → code → deploy → feedback captured"
      - "% of user feedback automatically categorized"
    
    developer_ecosystem:
      - "Number of custom integrations built with SDK"
      - "Community contributions (open source tools)"
      - "Third-party tool marketplace (future)"

  roadmap_notes: |
    Tools roadmap follows MVP → Ecosystem strategy:
    
    Phase 1 (Tier 1 MVP - Q1 2026):
      - Git Bridge (strategy ↔ code connection)
      - Deploy Tracker (production visibility)
      - Slack Bot (team adoption)
      - SDK (extensibility foundation)
    
    Phase 2 (Feedback Loops - Q2 2026):
      - Feedback Aggregator (user feedback)
      - CLI (developer productivity)
      - Meeting Assistant (capture decisions)
    
    Phase 3 (Intelligence - Q3 2026):
      - Workflow Automator (event-driven orchestration)
      - Analytics Connector (BI integration)
      - Insight Engine (proactive recommendations)
    
    Phase 4 (Enterprise - Q4 2026):
      - SSO Connector (enterprise identity)
      - Audit Logger (compliance)
      - API Gateway (enterprise security)
    
    Success criteria: Each tool validates integration pattern before scaling.
    Network effects emerge as tools interact (e.g., Git Bridge + Deploy Tracker
    create complete feature lifecycle visibility).

layers:
  - id: integration-tools
    name: Integration Tools
    active: true
    description: |
      Suite of tools that connect Emergent knowledge platform to external systems
      and developer workflows. Includes Git Bridge, Deploy Tracker, Slack Bot,
      SDK, and CLI for closing feedback loops between strategy, code, and users.
    components:
      - id: code-integration
        name: Code Integration
        active: false
        subs:
          - id: git-bridge
            name: Git Bridge
            active: false
          - id: sdk
            name: Developer SDK
            active: false
      - id: deployment-observability
        name: Deployment & Observability
        active: false
        subs:
          - id: deploy-tracker
            name: Deploy Tracker
            active: false
      - id: collaboration-tools
        name: Collaboration Tools
        active: false
        subs:
          - id: slack-bot
            name: Slack Bot
            active: false
          - id: cli
            name: Command Line Interface
            active: false
