#!/bin/bash
# Bootstrap remote Zitadel instance (dev environment)
# This script provisions a remote Zitadel instance using the same automation as local dev
# All configuration is done remotely via API calls, no direct host manipulation needed

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Configuration
REMOTE_HOST="${REMOTE_HOST:-root@94.130.12.194}"
REMOTE_APP_DIR="${REMOTE_APP_DIR:-/data/coolify/applications/nw0wokswsooooo4g0c0ggok4}"
# Note: Coolify docker-compose has a typo with ./ in the volume path
REMOTE_SECRETS_DIR="$REMOTE_APP_DIR./secrets"
LOCAL_SECRETS_DIR="./secrets-dev"

# Zitadel configuration
ZITADEL_DOMAIN="${ZITADEL_DOMAIN:-zitadel.dev.emergent-company.ai}"
ZITADEL_PORT="${ZITADEL_PORT:-8100}"
ZITADEL_PROTOCOL="${ZITADEL_PROTOCOL:-http}"  # http for now, will be https once DNS works

# Organization configuration
ORG_NAME="${ORG_NAME:-Spec Organization Dev}"
PROJECT_NAME="${PROJECT_NAME:-Spec Server Dev}"

# User configuration
ADMIN_USER_EMAIL="${ADMIN_USER_EMAIL:-admin@dev.spec.local}"
ADMIN_USER_PASSWORD="${ADMIN_USER_PASSWORD:-DevAdmin123!}"
TEST_USER_EMAIL="${TEST_USER_EMAIL:-test@dev.spec.local}"
TEST_USER_PASSWORD="${TEST_USER_PASSWORD:-DevTest123!}"

# Application configuration
OAUTH_APP_NAME="${OAUTH_APP_NAME:-Spec Server OAuth Dev}"
REDIRECT_URI="${REDIRECT_URI:-http://localhost:5175/auth/callback}"

echo -e "${BLUE}========================================${NC}"
echo -e "${BLUE}  Remote Zitadel Bootstrap (Dev Env)${NC}"
echo -e "${BLUE}========================================${NC}"
echo ""
echo -e "${GREEN}Configuration:${NC}"
echo "  Remote Host: $REMOTE_HOST"
echo "  Zitadel URL: $ZITADEL_PROTOCOL://$ZITADEL_DOMAIN:$ZITADEL_PORT"
echo "  Organization: $ORG_NAME"
echo "  Project: $PROJECT_NAME"
echo "  Admin Email: $ADMIN_USER_EMAIL"
echo "  Test Email: $TEST_USER_EMAIL"
echo ""

# Check prerequisites
echo -e "${GREEN}Checking prerequisites...${NC}"

if ! command -v ssh &> /dev/null; then
    echo -e "${RED}❌ ssh not found${NC}"
    exit 1
fi

if ! command -v jq &> /dev/null; then
    echo -e "${RED}❌ jq not found (brew install jq)${NC}"
    exit 1
fi

if ! command -v curl &> /dev/null; then
    echo -e "${RED}❌ curl not found${NC}"
    exit 1
fi

echo -e "${GREEN}✅ Prerequisites OK${NC}"
echo ""

# Step 1: Check if Zitadel is accessible
echo -e "${GREEN}Step 1: Checking Zitadel accessibility...${NC}"

# First try via domain (if DNS is configured)
if curl -s -f "$ZITADEL_PROTOCOL://$ZITADEL_DOMAIN:$ZITADEL_PORT/debug/healthz" > /dev/null 2>&1; then
    ZITADEL_URL="$ZITADEL_PROTOCOL://$ZITADEL_DOMAIN:$ZITADEL_PORT"
    echo -e "${GREEN}✅ Zitadel accessible via domain: $ZITADEL_URL${NC}"
else
    # Fall back to IP
    echo -e "${YELLOW}⚠️  Domain not accessible, trying IP...${NC}"
    SERVER_IP=$(echo "$REMOTE_HOST" | grep -oE '([0-9]{1,3}\.){3}[0-9]{1,3}' || echo "")
    if [ -z "$SERVER_IP" ]; then
        echo -e "${RED}❌ Could not extract server IP from REMOTE_HOST${NC}"
        exit 1
    fi
    
    if curl -s -f "$ZITADEL_PROTOCOL://$SERVER_IP:$ZITADEL_PORT/debug/healthz" > /dev/null 2>&1; then
        ZITADEL_URL="$ZITADEL_PROTOCOL://$SERVER_IP:$ZITADEL_PORT"
        echo -e "${GREEN}✅ Zitadel accessible via IP: $ZITADEL_URL${NC}"
        echo -e "${YELLOW}⚠️  Note: Using IP. Configure DNS for production use.${NC}"
    else
        echo -e "${RED}❌ Zitadel not accessible${NC}"
        echo ""
        echo "Troubleshooting:"
        echo "  1. Check if Zitadel container is running:"
        echo "     ssh $REMOTE_HOST 'docker ps | grep zitadel'"
        echo ""
        echo "  2. Check Zitadel logs:"
        echo "     ssh $REMOTE_HOST 'cd $REMOTE_APP_DIR && docker compose logs zitadel'"
        echo ""
        echo "  3. Verify ports are exposed:"
        echo "     ssh $REMOTE_HOST 'netstat -tlnp | grep 8100'"
        exit 1
    fi
fi

echo ""

# Step 2: Wait for PAT file to be generated
echo -e "${GREEN}Step 2: Waiting for bootstrap PAT...${NC}"
echo "Zitadel should have generated a PAT file on first startup"
echo ""

MAX_WAIT=60
WAIT_COUNT=0

while [ $WAIT_COUNT -lt $MAX_WAIT ]; do
    if ssh "$REMOTE_HOST" "test -f '$REMOTE_SECRETS_DIR/bootstrap/pat.txt' && test -s '$REMOTE_SECRETS_DIR/bootstrap/pat.txt'"; then
        PAT=$(ssh "$REMOTE_HOST" "cat '$REMOTE_SECRETS_DIR/bootstrap/pat.txt'" | tr -d '\n\r ')
        
        if [ -n "$PAT" ]; then
            echo -e "${GREEN}✅ Bootstrap PAT found${NC}"
            break
        fi
    fi
    
    WAIT_COUNT=$((WAIT_COUNT + 1))
    echo -n "."
    sleep 1
done

echo ""

if [ -z "$PAT" ]; then
    echo -e "${RED}❌ Bootstrap PAT not found after ${MAX_WAIT}s${NC}"
    echo ""
    echo "The PAT file should be auto-generated by Zitadel on first startup."
    echo ""
    echo "Check if zitadel.env contains machine user configuration:"
    echo "  ssh $REMOTE_HOST 'cat $REMOTE_APP_DIR/zitadel.env | grep MACHINE'"
    echo ""
    echo "Check Zitadel logs for PAT generation:"
    echo "  ssh $REMOTE_HOST 'cd $REMOTE_APP_DIR && docker compose logs zitadel | grep -i pat'"
    exit 1
fi

echo ""

# Step 3: Test authentication
echo -e "${GREEN}Step 3: Testing PAT authentication...${NC}"

AUTH_TEST=$(curl -s -w "\n%{http_code}" -X GET \
    "$ZITADEL_URL/auth/v1/users/me" \
    -H "Authorization: Bearer $PAT" 2>/dev/null || echo -e "\n000")

HTTP_CODE=$(echo "$AUTH_TEST" | tail -n1)

if [ "$HTTP_CODE" != "200" ]; then
    echo -e "${RED}❌ PAT authentication failed (HTTP $HTTP_CODE)${NC}"
    echo ""
    echo "Response:"
    echo "$AUTH_TEST" | sed '$d' | jq '.' 2>/dev/null || echo "$AUTH_TEST"
    exit 1
fi

echo -e "${GREEN}✅ PAT authentication successful${NC}"
echo ""

# Step 4: Create organization
echo -e "${GREEN}Step 4: Creating organization '$ORG_NAME'...${NC}"

ORG_RESPONSE=$(curl -s -w "\n%{http_code}" -X POST \
    "$ZITADEL_URL/management/v1/orgs" \
    -H "Authorization: Bearer $PAT" \
    -H "Content-Type: application/json" \
    -d "{\"name\": \"$ORG_NAME\"}" 2>/dev/null)

HTTP_CODE=$(echo "$ORG_RESPONSE" | tail -n1)
ORG_DATA=$(echo "$ORG_RESPONSE" | sed '$d')

if [ "$HTTP_CODE" = "200" ] || [ "$HTTP_CODE" = "201" ]; then
    ORG_ID=$(echo "$ORG_DATA" | jq -r '.id')
    echo -e "${GREEN}✅ Organization created: $ORG_ID${NC}"
elif echo "$ORG_DATA" | jq -r '.message' 2>/dev/null | grep -q "already exists"; then
    echo -e "${YELLOW}⚠️  Organization already exists, fetching ID...${NC}"
    
    # List orgs and find by name
    ORGS_LIST=$(curl -s -X POST \
        "$ZITADEL_URL/management/v1/orgs/_search" \
        -H "Authorization: Bearer $PAT" \
        -H "Content-Type: application/json" \
        -d '{"queries":[]}' 2>/dev/null)
    
    ORG_ID=$(echo "$ORGS_LIST" | jq -r ".result[] | select(.name == \"$ORG_NAME\") | .id" | head -1)
    
    if [ -n "$ORG_ID" ] && [ "$ORG_ID" != "null" ]; then
        echo -e "${GREEN}✅ Found existing organization: $ORG_ID${NC}"
    else
        echo -e "${RED}❌ Could not find organization${NC}"
        exit 1
    fi
else
    echo -e "${RED}❌ Failed to create organization (HTTP $HTTP_CODE)${NC}"
    echo "$ORG_DATA" | jq '.' 2>/dev/null || echo "$ORG_DATA"
    exit 1
fi

echo ""

# Step 5: Create project
echo -e "${GREEN}Step 5: Creating project '$PROJECT_NAME'...${NC}"

PROJECT_RESPONSE=$(curl -s -w "\n%{http_code}" -X POST \
    "$ZITADEL_URL/management/v1/projects" \
    -H "Authorization: Bearer $PAT" \
    -H "x-zitadel-orgid: $ORG_ID" \
    -H "Content-Type: application/json" \
    -d "{
        \"name\": \"$PROJECT_NAME\",
        \"projectRoleAssertion\": true,
        \"projectRoleCheck\": true
    }" 2>/dev/null)

HTTP_CODE=$(echo "$PROJECT_RESPONSE" | tail -n1)
PROJECT_DATA=$(echo "$PROJECT_RESPONSE" | sed '$d')

if [ "$HTTP_CODE" = "200" ] || [ "$HTTP_CODE" = "201" ]; then
    PROJECT_ID=$(echo "$PROJECT_DATA" | jq -r '.id')
    echo -e "${GREEN}✅ Project created: $PROJECT_ID${NC}"
elif echo "$PROJECT_DATA" | jq -r '.message' 2>/dev/null | grep -q "already exists"; then
    echo -e "${YELLOW}⚠️  Project already exists, fetching ID...${NC}"
    
    # List projects and find by name
    PROJECTS_LIST=$(curl -s -X POST \
        "$ZITADEL_URL/management/v1/projects/_search" \
        -H "Authorization: Bearer $PAT" \
        -H "x-zitadel-orgid: $ORG_ID" \
        -H "Content-Type: application/json" \
        -d '{"queries":[]}' 2>/dev/null)
    
    PROJECT_ID=$(echo "$PROJECTS_LIST" | jq -r ".result[] | select(.name == \"$PROJECT_NAME\") | .id" | head -1)
    
    if [ -n "$PROJECT_ID" ] && [ "$PROJECT_ID" != "null" ]; then
        echo -e "${GREEN}✅ Found existing project: $PROJECT_ID${NC}"
    else
        echo -e "${RED}❌ Could not find project${NC}"
        exit 1
    fi
else
    echo -e "${RED}❌ Failed to create project (HTTP $HTTP_CODE)${NC}"
    echo "$PROJECT_DATA" | jq '.' 2>/dev/null || echo "$PROJECT_DATA"
    exit 1
fi

echo ""

# Create local secrets directory
mkdir -p "$LOCAL_SECRETS_DIR"

# Save IDs locally
cat > "$LOCAL_SECRETS_DIR/config.env" << EOF
# Remote Zitadel Configuration (Dev Environment)
# Generated: $(date)

ZITADEL_URL=$ZITADEL_URL
ZITADEL_DOMAIN=$ZITADEL_DOMAIN
ZITADEL_ORG_ID=$ORG_ID
ZITADEL_PROJECT_ID=$PROJECT_ID

# Copy these to your Coolify environment variables:
#   ZITADEL_ORG_ID=$ORG_ID
#   ZITADEL_PROJECT_ID=$PROJECT_ID
EOF

echo -e "${GREEN}✅ Configuration saved to: $LOCAL_SECRETS_DIR/config.env${NC}"
echo ""

# Summary
echo -e "${BLUE}========================================${NC}"
echo -e "${BLUE}  Bootstrap Complete!${NC}"
echo -e "${BLUE}========================================${NC}"
echo ""
echo -e "${GREEN}Organization:${NC} $ORG_NAME"
echo -e "${GREEN}Organization ID:${NC} $ORG_ID"
echo ""
echo -e "${GREEN}Project:${NC} $PROJECT_NAME"
echo -e "${GREEN}Project ID:${NC} $PROJECT_ID"
echo ""
echo -e "${YELLOW}Next Steps:${NC}"
echo ""
echo "1. Update Coolify environment variables:"
echo "   ZITADEL_ORG_ID=$ORG_ID"
echo "   ZITADEL_PROJECT_ID=$PROJECT_ID"
echo ""
echo "2. Configure DNS for full functionality:"
echo "   *.dev.emergent-company.ai  A  94.130.12.194"
echo ""
echo "3. Once DNS is configured, access Zitadel console at:"
echo "   https://$ZITADEL_DOMAIN"
echo ""
echo "4. Create OAuth and API applications manually in Zitadel console:"
echo "   - OAuth OIDC App for frontend authentication"
echo "   - API Application for backend service authentication"
echo "   - Service accounts for programmatic access"
echo ""
echo "5. Or run the full bootstrap script on the server:"
echo "   ssh $REMOTE_HOST 'cd $REMOTE_APP_DIR && bash scripts/bootstrap-zitadel-fully-automated.sh provision'"
echo ""

# Save summary
cat > "$LOCAL_SECRETS_DIR/BOOTSTRAP_SUMMARY.md" << EOF
# Remote Zitadel Bootstrap Summary

**Date:** $(date)
**Environment:** Development (dev.emergent-company.ai)

## Configuration

- **Zitadel URL:** $ZITADEL_URL
- **Domain:** $ZITADEL_DOMAIN
- **Organization:** $ORG_NAME
- **Organization ID:** $ORG_ID
- **Project:** $PROJECT_NAME
- **Project ID:** $PROJECT_ID

## Coolify Environment Variables

Add these to your Coolify deployment:

\`\`\`bash
ZITADEL_DOMAIN=$ZITADEL_DOMAIN
ZITADEL_ORG_ID=$ORG_ID
ZITADEL_PROJECT_ID=$PROJECT_ID
\`\`\`

## DNS Configuration

Configure wildcard DNS to enable domain access:

\`\`\`
*.dev.emergent-company.ai  A  94.130.12.194
\`\`\`

## Access

Once DNS is configured:

- **Zitadel Console:** https://$ZITADEL_DOMAIN
- **Database:** db.dev.emergent-company.ai:5432
- **API:** (configure after application deployment)

## Next Steps

1. Configure DNS records
2. Update Coolify environment variables
3. Create OAuth applications in Zitadel console
4. Deploy application services
5. Test authentication flow

## Credentials

**Admin Console Access:**
- Email: $ADMIN_USER_EMAIL
- Password: $ADMIN_USER_PASSWORD

**Test User:**
- Email: $TEST_USER_EMAIL  
- Password: $TEST_USER_PASSWORD

(Note: Users need to be created manually in Zitadel console or via full bootstrap)
EOF

echo -e "${GREEN}✅ Summary saved to: $LOCAL_SECRETS_DIR/BOOTSTRAP_SUMMARY.md${NC}"
echo ""
